### ISSUE TITLE
version of GHC for the book

### ISSUE THREAD

**Issue by ulysses4ever** [input-output-hk/hs-opt-handbook.github.io#76]
I noticed two conflicting directions:

- https://github.com/input-output-hk/hs-opt-handbook.github.io/blob/dcf7054c8d9d89923e94faf0585c3a26def7ec19/index.rst?plain=1#L8

- https://github.com/input-output-hk/hs-opt-handbook.github.io/blob/dcf7054c8d9d89923e94faf0585c3a26def7ec19/src/Preliminaries/how_to_use.rst?plain=1#L33

Maybe some sort of a constant would be useful to reference the required version of GHC...

**Comment by doyougnu** [comment]
Aha! Thanks for the review. Yes I must have missed this in when I updated the version. Constants would be nice, and would be my normal operating procedure with latex but sphinx makes it harder than it should be. Let me test some adding these in the `rst_prolog` and see if it works.

**Comment by ulysses4ever** [comment]
Nice!
